-d D:\OneDrive\GIt\HardwareDesign\KeyTunePlayer\impl\gwsynthesis\KeyTunePlayer.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cst D:\OneDrive\GIt\HardwareDesign\KeyTunePlayer\src\KeyTunePlayer.cst
-cfg D:\OneDrive\GIt\HardwareDesign\KeyTunePlayer\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
